@start=2023-07-01T11:32:51Z
@end=2023-07-31T20:42:51Z
@category1=Zoomba

GET {{host}}/subscriptions/{{subscriptionId}}/gyms/{{gymId}}/sessions?startDateTime={{start}}&endDateTime={{end}}&categories={{category1}}

### no date time
GET {{host}}/subscriptions/{{subscriptionId}}/gyms/{{gymId}}/sessions?categories={{category1}}

### no categories
GET {{host}}/subscriptions/{{subscriptionId}}/gyms/{{gymId}}/sessions?startDateTime={{start}}&endDateTime={{end}}

### no categories or date time
GET {{host}}/subscriptions/{{subscriptionId}}/gyms/{{gymId}}/sessions